// =======================
// AUTO-GENERATED BY CUCC, DO NOT EDIT
#include "cucpu.hpp"
#include <array>
using namespace cucpu;

// declarations are re-written by transpiler
#define __global__
#define __device__
#define __host__
#define __forceinline__ inline
#define __restrict__
#define __shared__ 
#define __syncthreads() ::cucpu::syncthreads()
// =======================
// 2D 3x3 box blur (stencil). Exercises 2D grid/block launches with dim3, the
// .y components of the built-in index variables, and 2D array indexing. No
// __shared__ / __syncthreads() so this runs on the fast launch engine.
//
// The kernel result is checked against a serial CPU reference inside main().
// Expected output: "stencil: OK"
#include <cstdio>

__global__ void box_blur(const int *in, int *out, int w, int h) {
  int x = blockIdx.x * blockDim.x + threadIdx.x;
  int y = blockIdx.y * blockDim.y + threadIdx.y;
  if (x >= w || y >= h)
    return;

  int sum = 0, count = 0;
  for (int dy = -1; dy <= 1; dy++) {
    for (int dx = -1; dx <= 1; dx++) {
      int nx = x + dx, ny = y + dy;
      if (nx >= 0 && nx < w && ny >= 0 && ny < h) {
        sum += in[ny * w + nx];
        count++;
      }
    }
  }
  out[y * w + x] = sum / count;
}

int main() {
  const int w = 64, h = 48, n = w * h;
  int *hin = new int[n];
  for (int y = 0; y < h; y++)
    for (int x = 0; x < w; x++)
      hin[y * w + x] = (x * 7 + y * 13) % 97;

  int *din, *dout;
  cudaMalloc((void **)&din, n * sizeof(int));
  cudaMalloc((void **)&dout, n * sizeof(int));
  cudaMemcpy(din, hin, n * sizeof(int), cudaMemcpyHostToDevice);

  dim3 block(16, 16);
  dim3 grid((w + block.x - 1) / block.x, (h + block.y - 1) / block.y);
  ::cucpu::launch_fast(box_blur, grid, block, din, dout, w, h);
  cudaDeviceSynchronize();

  int *hout = new int[n];
  cudaMemcpy(hout, dout, n * sizeof(int), cudaMemcpyDeviceToHost);

  // serial reference
  int mismatches = 0;
  for (int y = 0; y < h; y++) {
    for (int x = 0; x < w; x++) {
      int sum = 0, count = 0;
      for (int dy = -1; dy <= 1; dy++)
        for (int dx = -1; dx <= 1; dx++) {
          int nx = x + dx, ny = y + dy;
          if (nx >= 0 && nx < w && ny >= 0 && ny < h) {
            sum += hin[ny * w + nx];
            count++;
          }
        }
      if (hout[y * w + x] != sum / count)
        mismatches++;
    }
  }
  std::printf("stencil: %s\n", mismatches == 0 ? "OK" : "FAIL");

  cudaFree(din);
  cudaFree(dout);
  delete[] hin;
  delete[] hout;
  return 0;
}